# Data path. adjust them!
common:
    image_file: "/home/sush/catkin_ws/src/extended_lidar_camera_calib/floam/PCD/sep_5_2.png"
    pcd_file: "/home/sush/catkin_ws/src/extended_lidar_camera_calib/floam/PCD/sep_5_2.pcd"
    # image_file: "/home/sush/catkin_ws/src/extended_lidar_camera_calib/floam/PCD/aug_17_1.png"
    # pcd_file: "/home/sush/catkin_ws/src/extended_lidar_camera_calib/floam/PCD/aug_17_1_sliced_2.pcd"
    result_file: "/home/sush/catkin_ws/extrinsic.txt"

# Camera Parameters. Adjust them!
camera:
    # Pt_Grey
    # camera_matrix: [778.36585, 0.0,         702.1301,
    #                 0.0,       778.14272,   533.29078,
    #                 0.0,       0.0,         1.0     ]
    # dist_coeffs: [-0.028278, 0.038808, 0.000716, -0.000385, 0.0]

    # Realsense (FROM ROS_INFO)
    # camera_matrix: [642.0465087890625,  0.0,              656.24072265625,
    #                 0.0,                641.32958984375,  364.64154052734375,
    #                 0.0,                0.0,              1.0]
    # dist_coeffs: [-0.058568429201841354, 0.07027624547481537, -0.0002667765074875206, 0.0009609074331820011, -0.02324339933693409]
    # dist_coeffs: [0.0, 0.0, 0.0, 0.0, 0.0]

    # Realsense (FROM REALSENSE-VIEWER)
    camera_matrix: [653.317,  0.0,      645.998,
                    0.0,      653.317,  360.754,
                    0.0,      0.0,      1.0]
    dist_coeffs: [0.0, 0.0, 0.0, 0.0, 0.0]

# Calibration Parameters.!
calib:
    calib_config_file: "/home/sush/catkin_ws/src/extended_lidar_camera_calib/livox_camera_calib/config/config_indoor.yaml"
    use_rough_calib: true # set true if your initial_extrinsic is bad
