# Data path. adjust them!
common:
    image_file: "/home/sush/catkin_ws/src/extended_lidar_camera_calib/floam/PCD/aug_17_1.png"
    pcd_file: "/home/sush/catkin_ws/src/extended_lidar_camera_calib/floam/PCD/aug_17_1_sliced_2.pcd"
    result_file: "/home/sush/catkin_ws/extrinsic.txt"

# Camera Parameters. Adjust them!
camera:
    # camera_matrix: [1364.45, 0.0,      958.327,
    #                 0.0,     1366.46,  535.074,
    #                 0.0,     0.0,      1.0     ]
    # dist_coeffs: [0.0958277, -0.198233, -0.000147133, -0.000430056, 0.000000]
    camera_matrix: [778.36585, 0.0,         702.1301,
                    0.0,       778.14272,   533.29078,
                    0.0,       0.0,         1.0     ]
    dist_coeffs: [-0.028278, 0.038808, 0.000716, -0.000385, 0.0]

# Calibration Parameters.!
calib:
    calib_config_file: "/home/sush/catkin_ws/src/extended_lidar_camera_calib/livox_camera_calib/config/config_indoor.yaml"
    use_rough_calib: true # set true if your initial_extrinsic is bad
